apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  database_url: "mongodb://localhost:27017"
  # log_level: "debug"
  api_endpoint: "https://xrx4jghx2b.execute-api.us-east-2.amazonaws.com/v1/getenvironment/1"
  db_user: admin
  db_password: 
---
# ===================== connecting to pod ===================
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: database_url
    - name: API_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: api_endpoint