apiVersion: v1
kind: Service
metadata: 
  name: my-service
spec:
  selector: 
    app: my-app  # this should match with the metadata name given in our pod.yml
  ports:
    - protocol: TCP 
      port: 80  # service port
      targetPort: 8080  # pod port / application port
      nodePort: 30021
  type: NodePort